{
  stub(mock.add("ExceptionOne")).andThrows(new ExceptionOne());
  stub(mock.getLast()).andReturn("last");
  stubVoid(mock).toThrow(new ExceptionTwo()).on().clear();
  stubVoid(mockTwo).toThrow(new ExceptionThree()).on().clear();
  stub(mockTwo.containsValue("ExceptionFour")).andThrows(new ExceptionFour());
  stub(mockTwo.get("Are you there?")).andReturn("Yes!");
  assertNull(mockTwo.get("foo"));
  assertTrue(mockTwo.keySet().isEmpty());
  assertEquals("Yes!",mockTwo.get("Are you there?"));
  try {
    mockTwo.clear();
    fail();
  }
 catch (  ExceptionThree e) {
  }
  try {
    mockTwo.containsValue("ExceptionFour");
    fail();
  }
 catch (  ExceptionFour e) {
  }
  assertNull(mock.getFirst());
  assertEquals("last",mock.getLast());
  try {
    mock.add("ExceptionOne");
    fail();
  }
 catch (  ExceptionOne e) {
  }
  try {
    mock.clear();
    fail();
  }
 catch (  ExceptionTwo e) {
  }
}
