{
  mock.simpleMethodWithArgument("3");
  mock.simpleMethodWithArgument("3");
  replay(mock);
  try {
    mock.simpleMethodWithArgument("5");
    fail();
  }
 catch (  AssertionError expected) {
    assertEquals("\n  Unexpected method call simpleMethodWithArgument(\"5\"):" + "\n    simpleMethodWithArgument(\"3\"): expected: 2, actual: 0",expected.getMessage());
  }
}
